-- return {
--   "hrsh7th/nvim-cmp",
--   opts = {
--     window = {
--       completion = {
--         border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
--         winhighlight = "Normal:CmpPmenu,FloatBorder:NoicePopupBorder,CursorLine:PmenuSel,Search:None",
--       },
--       documentation = {
--         border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
--         winhighlight = "Normal:CmpPmenu,FloatBorder:NoicePopupBorder,CursorLine:PmenuSel,Search:None",
--       },
--     },
--   },
-- }
